spring:
  application:
    name: eureka-client
user:
  role: Admin UAT refresh test auto refresh call from webhook 123

welcome:
  message: Welcome to the Spring Cloud Config managed application! call from webhook 123
